version: '2'
services:
  snapanonyme-mysql:
    image: mysql
    # set default mysql data, change as needed at run time
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=snapanonyme
      - MYSQL_PASSWORD=snapanonyme
      - MYSQL_DATABASE=snapanonyme
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

