version: '2'
services:
  snapanonyme-mysql:
    image: mysql:5.7.20
    # set default mysql data, change as needed at run time
    environment:
      - MYSQL_USER=snapanonyme
      - MYSQL_PASSWORD=snapanonyme
      - MYSQL_DATABASE=snapanonyme
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
