spring:
  application:
    name: snapanonyme
  ## MULTIPART (MultipartProperties)
  # Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB

  datasource:
    url: jdbc:mysql://localhost:3306/snapanonyme?createDatabaseIfNotExist=true
    username: snapanonyme
    password: snapanonyme
    # TODO Set database uri ,username and pwd dynamically via env var when starting the app
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  ## Hibernate Logging
  logging:
    level:
      org.hibernate.SQL: DEBUG





server:
  port: 9000