FROM jenkins/jenkins:lts

#RUN version=2.89 && sha=$(curl -q -fsSL "https://repo.jenkins-ci.org/releases/org/jenkins-ci/main/jenkins-war/${version}/jenkins-war-${version}.war.sha256" )
#
ENV SNAPANONYM_DB_HOST=127.0.0.1\
    SNAPANONYM_DB_PORT=3306\
    SNAPANONYM_DB_NAME=snapanonyme\
    SNAPANONYM_DB_USER=snapanonyme\
    SNAPANONYM_DB_PASSWORD=snapanonyme
